### ISSUE TITLE
Provides samples wont work under Windows and curl 7.55.1

### ISSUE THREAD

**Issue by hfrmobile** [hella-info/onyx_api#1]
Documentation does not mention platform (Linux or Windows).

Data:
`-d '{"code" : "H99xV2yT"}'` does **not work** for me

`-d "{\"code\" : \"H99xV2yT\"}"` **does work** for me.

**Comment by profer** [comment]
Thank's for the input! We've now added information about the shell and OS used in the example code to the documentation.
