### ISSUE TITLE
actual_position/actual_angle not reported as target_position/target_angle

### ISSUE THREAD

**Issue by muhlba91** [hella-info/onyx_api#3]
When sending the command to set a certain target position or angle, the raffstore/shutter performs the action correctly.
However, polling the device's state through the API does not report back success by setting the `actual_position`/`actual_angle` to the new value (the `target_position`/`target_angle`).

Interestingly, it seems the value gets updated either:
- on issuing a new command (e.g. sending a STOP or any other command updates the value immediately),
- tests showed that the value seems to be updated periodically every ~5 minutes (value deducted from observation)

Is this  behaviour working as designed or do I have a possibility to receive those value updates faster?

**Comment by profer** [comment]
This is true and working as designed. To conserve radio bandwidth our devices only transmit property updates on their own when an unexpected event (e.g. a button press) happens. Clients have to calculate the current `actual_*` property values by interpolating between the `actual_*` and `target_*` properties based on their timestamp and the `drivetime_up`, `drivetime_down` and `rotation_time` properties.

We also perform periodic property updates roughly every 5 minutes as you already noticed. This is mainly to detect offline devices and recover from packet loss. We add a random jitter to the update interval to reduce interference from neighbouring ONYX systems.

**Comment by muhlba91** [comment]
Awesome, this explains the `drivetime_*` and ` rotation_time` properties and helps a lot already! :)
