### ISSUE TITLE
Documentation: API version v1/v2

### ISSUE THREAD

**Issue by muhlba91** [hella-info/onyx_api#4]
According to the API `/version` the devices support API versions `v1` and `v2`.
Is there an updated documentation available on what changed, or especially got added, in `v2`?

**Comment by profer** [comment]
API v2 added a new `/events` endpoint which can be used to observe changes to devices and their properties without having to poll all the time. To use the new API you send  a GET request to `/api/v2/events` and keep the connection open to receive updates.

Messages are sent as JSON, separated by two newline characters. The first message is always a snapshot of the current state of all devices which clients need to store. Each following message is a [JSON Merge Patch](https://tools.ietf.org/html/rfc7386) that clients can apply to their copy of the device state to update it.

Sorry that the documentation is not updated vor API v2 yet, I hope this short summary is of help in the meantime.

**Comment by muhlba91** [comment]
Sounds great - this helps a lot! :+1:

This new `/events` endpoint is like a WebSocket Upgrade connection or do I have to manually keep the connection open on client's side?

**Comment by profer** [comment]
Its a GET request with an undetermined response body length so you don't have to perform a web socket upgrade. Using aiohttp you can just keep reading lines from the HTTP response: https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-response-content

You can also just use curl to observe the event stream:

`curl -s -H "Authorization: Bearer AUTH_TOKEN" https://api.hella.link/box/FINGERPRINT/api/v2/events`

**Comment by muhlba91** [comment]
Awesome, thanks a lot for that explanation and the links provided! :)
